// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Wd5h8lUJSHgtpfPAaJkg0uG-KzQHT78',
    appId: '1:675972461424:web:a666920d3e6dadba19d5b5',
    messagingSenderId: '675972461424',
    projectId: 'my-wedding-ef991',
    authDomain: 'my-wedding-ef991.firebaseapp.com',
    storageBucket: 'my-wedding-ef991.firebasestorage.app',
    measurementId: 'G-YH3G95Q0LG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9TZuhNiUINh6FN8NuBq3CSIwapSbFoVY',
    appId: '1:675972461424:android:a3a223db5a82eb6f19d5b5',
    messagingSenderId: '675972461424',
    projectId: 'my-wedding-ef991',
    storageBucket: 'my-wedding-ef991.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbFCAnjtXI5lak3AKQKRCcjqWSW6cFf0M',
    appId: '1:675972461424:ios:6cc1e49b4583c15919d5b5',
    messagingSenderId: '675972461424',
    projectId: 'my-wedding-ef991',
    storageBucket: 'my-wedding-ef991.firebasestorage.app',
    iosBundleId: 'com.example.weddingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbFCAnjtXI5lak3AKQKRCcjqWSW6cFf0M',
    appId: '1:675972461424:ios:6cc1e49b4583c15919d5b5',
    messagingSenderId: '675972461424',
    projectId: 'my-wedding-ef991',
    storageBucket: 'my-wedding-ef991.firebasestorage.app',
    iosBundleId: 'com.example.weddingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7Wd5h8lUJSHgtpfPAaJkg0uG-KzQHT78',
    appId: '1:675972461424:web:29e87f175c24099819d5b5',
    messagingSenderId: '675972461424',
    projectId: 'my-wedding-ef991',
    authDomain: 'my-wedding-ef991.firebaseapp.com',
    storageBucket: 'my-wedding-ef991.firebasestorage.app',
    measurementId: 'G-X2P2WFS6ZY',
  );
}
